### ISSUE TITLE
Epoch marker entropy value

### ISSUE THREAD

**Issue by davxy** [gavofyork/graypaper#125]
Since for the block seal we’re using $\eta[3]$, this effectively establishes $\eta[3]$ as a required value for blocks verification.

Suppose we announce the epoch marker $H_e$ during epoch $N−1$. It  includes:
- Fallback validator keys for epoch N (for use if the epochal lottery fails to complete).
- $\eta[1]$ as in epoch $N−1$ (which corresponds to $\eta[2]$ of epoch $N$).

Now, if this announcement must be really for light clients who want to verify block seals, it might be more advantageous to include $\eta[2]$ as in epoch $N−1$ ​ (corresponding to $\eta[3]$ of epoch $N$). This way, $H_e$​, and optionally $H_t$​, would be sufficient for light clients to verify seals for epoch $N$ blocks.

Including only $\eta[1]$ (as we're doing now) requires the light client to use two $H_e$​ markers: the one from epoch $N−1$ (for the fallback keys sequence) and the one from epoch $N−2$ (for the entropy).

What about modifying $H_e$ to **also** include $\eta[2]$ for convenience? 

Including $\eta[1]$ is still useful as it is used to shuffle the keys in case of fallback and it is set as **the epochal entropy** which can be used to check for core assignments, etc.

**Comment by davxy** [comment]
This is not a request, but rather a prompt for reflection on the matter

**Comment by gavofyork** [comment]
That sounds reasonable. Want to make a PR?
