### ISSUE TITLE
PVM Instructions in 0.5 vs 0.4.5

### ISSUE THREAD

**Issue by sourabhniyogi** [gavofyork/graypaper#158]
1. It appears mul_upper_s_s_imm + mul_upper_u_u_imm existed in 0.4.5 but disappeared in 0.5.0 -- is this intentional?
2. GP keeps a lot of 32-bit instructions alongside 64-bit instructions, creating a lot of "twins", which I tabulated in two columns [here](https://docs.google.com/spreadsheets/d/1R7syeL7GYq4KH2B3Zh03v3CAFnK1iNNF0J4c2r-vKWw/edit?gid=1743195954#gid=1743195954) labelled "32-bit twin" and "64-bit twin".  Is there a way to eliminate the 32-bit ones in favor of 64-bit? After all, the R in RISC-V = Reduced and we appear to have a bit of instruction bloat -- If this to support 32-bit and 64-bit simultaneously in GP/polkadot/JAM Rust SDK/..., may I suggest we cut out the 32-bit support by a certain date to make everyone's life easier, the sooner the better?
3. In A.5.10 -- why is there not store_ind_i8, store_ind_i16, store_ind_i32, store_ind_i64, load_ind_i64?

**Comment by koute** [comment]
1. Yes.
2. No. We are based on RISC-V, so there is a certain baseline of instructions and semantics we need to support.
3. There's no point. It's the same reason why there isn't `add_u64` and `add_i64`.
