### ISSUE TITLE
extra backtick and psi_k

### ISSUE THREAD

**Issue by qiweiii** [gavofyork/graypaper#23]
there is an extra backtick here:
https://github.com/gavofyork/graypaper/blob/92a6d47bd0022524c923b0677c92a046eb805016/text/judgements.tex#L20

and maybe there are some `\psi_\mathbf{k}` not completely removed after https://github.com/gavofyork/graypaper/commit/973ca32b7fa6e52e3d19eda7bfb1c7019067f32a, like this:

https://github.com/gavofyork/graypaper/blob/92a6d47bd0022524c923b0677c92a046eb805016/text/judgements.tex#L17

**Comment by gavofyork** [comment]
Fixed :)
